---
# Config of plugin BetterNick by HimmelKreis4865.
# If you can use {player} or {nick}, you'll see that on default text.

general:
  # Message, if player does not exists or is not online.
  notFound: §4The given playername is not found on the server
  # The message, if player tries an command without permission.
  nopermission: §cYou do not have the permission to execute this command
  # Help message, if player uses a wrong general syntax.
  help: "§e/nick set <nickname>\n§e/nick reset\n §e/nick adminset <player> <nickname>\n §e/nick adminreset <player>\n §e/nick realname <nickname>"

# A custom feature are nametags that uses PurePerms as Rank management.
ranks:
  # Set it to true to use ranks, if it's false, you can skip that category.
  enabled: false
  # the default-format is the default Rank Format, that is used for ranks which are not set.
  # IMPORTANT: Format is like prefix, so it's all before nametag.
  default-format: §7Default §8> §7
  # Here you have to set every rank that needs to have a custom format. List all ranks like the default ones.
  # IMPORTANT: Format is like prefix, so it's all before nametag.
  # If you're using PureChat, please make sure to make that format compatible with this one.
  format:
    Owner: §4Owner §7| §4
    Admin: §6Admin §7| §4
    Guest: §8[§7Guest§8] §7


# BetterNick command:
command:
  # set a name for the command
  name: nick
  # set the description for the command
  description: Change your own / other nick

# Command Argument 1: /nick <argument-1> customization part.
# those parts, you have to set:
# permsision: <permission>  -  Set a permission for executing.
# success: <message>  -  Set a success part for Argument (not for realname).
# syntax: <syntaxpart>  -  If players used it wrongly, he'll see this error message.

# IMPORTANT: All other parts are extra - explained.
set:
  permission: nick.set
  success: §8[§5Nick§8] §7You successfully set your nickname to §e{nick}§7.
  syntax: "§l§cSyntax: §r§7/nick set <nick>"

reset:
  permission: nick.reset
  success: §8[§5Nick§8] §7You successfully resest your nickname
  syntax: "§l§cSyntax: §r§7/nick reset"

adminset:
  permission: nick.adminset
  success: §8[§5Nick§8] §7You successfully set the nick of player §a{player} §7to §e{nick}§7.
  # successByOther: <message>  -  means, the message for player that nick was changed.
  successByOther: §8[§5Nick§8] §7Your nick was changed by player §a{player}§7 to §e{nick}§7.
  syntax: "§l§cSyntax: §r§7/nick adminset <player> <nick>"
adminreset:
  permission: nick.adminreset
  success: §8[§5Nick§8] §7You successfully reset the nick of player §a{player}§7.
  # successByOther: <message>  -  means, the message for player that nick was changed.
  successByOther: §8[§5Nick§8] §7Your nick was changed by player §a{player}§7.
  syntax: "§l§cSyntax: §r§7/nick adminreset <player>"

realname:
  syntax: "§l§cSyntax: §r§7/nick realname <nickname>"
  # ---- Message ----
  # Title of the message. Below, you'll see all player names.
  title: "§7----§8[§5Nick§8]§7----\n §eAll Players with a name includes the name you chose.\n"
  # Now the format for all Players that have a nickname that includes the given name.
  player: "§7 - §e{player} §6has the nickname §e{nickname}\n"
  # if no player is found with this combination, this message is sent
  no-player: "§cThere is no player with this nickname combination! You can use auto complete function, so just write some letters of the name"
...